// <auto-generated />
using Ballers.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Ballers.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518120000_AddFixtureCaptaincy")]
    partial class AddFixtureCaptaincy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
